# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024-2025 Univention GmbH

{{- if .Values.minio.enabled }}
{{- $nubusMasterPassword := include "nubusTemplates.masterPassword" . -}}
---
kind: "Secret"
apiVersion: "v1"
type: {{ .type | default "Opaque" | quote }}
metadata:
  name: {{ index .Values.minio.provisioning.usersExistingSecrets 0 | quote }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.additionalLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  {{- $policyReadWriteName := (index .Values.minio.provisioning.policies 0).name }}
  {{- $policyReadName := (index .Values.minio.provisioning.policies 1).name }}

  {{- $accessKey := coalesce .Values.nubusPortalConsumer.objectStorage.auth.accessKeyId (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-consumer-accesskey") | sha1sum) }}
  {{- $secretKey := coalesce .Values.nubusPortalConsumer.objectStorage.auth.secretAccessKey (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-consumer-secretkey") | sha1sum) }}
  portal-consumer-user: {{ printf "username=%s\npassword=%s\ndisabled=false\npolicies=%s\nsetPolicies=false" $accessKey $secretKey $policyReadWriteName | quote }}

  {{- $accessKey := coalesce .Values.nubusPortalServer.objectStorage.auth.accessKeyId (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-server-accesskey") | sha1sum) }}
  {{- $secretKey := coalesce .Values.nubusPortalServer.objectStorage.auth.secretAccessKey (print (derivePassword 1 "long" $nubusMasterPassword "nubus" "portal-server-secretkey") | sha1sum) }}
  portal-server-user: {{ printf "username=%s\npassword=%s\ndisabled=false\npolicies=%s\nsetPolicies=false" $accessKey $secretKey $policyReadName | quote }}
...
{{- end }}
